"use client";
import { useCallback, useEffect, useRef, useState } from "react";
type Building = "keep" | "house" | "farm" | "lumber";
const info: Record<Building, { name: string; icon: string; color: string }> = { keep: { name: "Town center", icon: "♜", color: "gold" }, house: { name: "Cottage", icon: "⌂", color: "rose" }, farm: { name: "Farmstead", icon: "✣", color: "wheat" }, lumber: { name: "Lumber camp", icon: "♒", color: "pine" } };
export function KingdomMap() {
  const [buildings, setBuildings] = useState<{ x: number; y: number; type: Building }[]>([{ x: 5, y: 4, type: "keep" }]); const [selected, setSelected] = useState<Building>("house"); const [pos, setPos] = useState({ x: 0, y: 0 }); const drag = useRef({ active: false, x: 0, y: 0, ox: 0, oy: 0 });
  const move = useCallback((e: PointerEvent) => { if (drag.current.active) setPos({ x: drag.current.ox + e.clientX - drag.current.x, y: drag.current.oy + e.clientY - drag.current.y }); }, []);
  useEffect(() => { const up = () => { drag.current.active = false; }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; }, [move]);
  useEffect(() => { const key = (e: KeyboardEvent) => { const a = e.shiftKey ? 42 : 22; if (e.key.includes("Arrow")) e.preventDefault(); if (e.key === "ArrowUp") setPos(p => ({ ...p, y: p.y + a })); if (e.key === "ArrowDown") setPos(p => ({ ...p, y: p.y - a })); if (e.key === "ArrowLeft") setPos(p => ({ x: p.x + a, y: p.y })); if (e.key === "ArrowRight") setPos(p => ({ x: p.x - a, y: p.y })); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  const place = (x: number, y: number) => { if (!buildings.some(b => b.x === x && b.y === y)) setBuildings(b => [...b, { x, y, type: selected }]); };
  return <main className="kingdom" onPointerDown={e => { drag.current = { active: true, x: e.clientX, y: e.clientY, ox: pos.x, oy: pos.y }; }}><div className="map-world" style={{ transform: `translate(calc(-50% + ${pos.x}px),calc(-50% + ${pos.y}px))` }}><div className="terrain terrain-one" /><div className="terrain terrain-two" /><div className="terrain terrain-three" /><div className="grid">{Array.from({ length: 121 }, (_, i) => { const x = i % 11; const y = Math.floor(i / 11); return <button key={i} className="tile" style={{ left: `${(x - y) * 68}px`, top: `${(x + y) * 34}px` }} onPointerDown={e => e.stopPropagation()} onClick={() => place(x, y)} aria-label={`Build on tile ${x}, ${y}`} />; })}{buildings.map(({ x, y, type }) => <div key={`${x}-${y}`} className={`building building-${type}`} style={{ left: `${(x - y) * 68}px`, top: `${(x + y) * 34 - 48}px` }}><span>{info[type].icon}</span><small>{info[type].name}</small></div>)}</div></div><header className="game-top"><div className="crest">✦</div><div><p className="eyebrow">THE FREE REALMS</p><h1>Kingdoms of Alderwood</h1></div><div className="season"><span className="sun">☼</span><div><b>High summer</b><small>Year 1 · Day 1</small></div></div></header><div className="map-hint">DRAG TO EXPLORE <span>·</span> ARROW KEYS TO PAN</div><aside className="build-panel" onPointerDown={e => e.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">YOUR SETTLEMENT</p><h2>Build your realm</h2></div><span className="free-pill">FREE</span></div><p className="panel-copy">Lay the first stones of your kingdom. Choose a structure, then select an open tile.</p><div className="build-list">{(["house", "farm", "lumber"] as Building[]).map(type => <button className={`build-option ${selected === type ? "is-selected" : ""}`} key={type} onClick={() => setSelected(type)}><span className={`option-icon ${info[type].color}`}>{info[type].icon}</span><span><b>{info[type].name}</b><small>Ready to build</small></span><i>＋</i></button>)}</div><div className="panel-foot"><span className="dot" /> All materials available</div></aside><div className="compass"><span>N</span><div>✦</div><small>W&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E</small></div><div className="scale">A L D E R W O O D&nbsp; · &nbsp;FREE MODE</div></main>;
}
