"use client";
import { useEffect, useRef, useState } from "react";
import { ArcRotateCamera, Color3, Color4, DirectionalLight, Engine, HemisphericLight, Mesh, MeshBuilder, Scene, StandardMaterial, Vector3 } from "@babylonjs/core";
type MaterialKey = "grass" | "sand" | "rock" | "gravel" | "wood" | "water";
type Block = { mesh: Mesh; x: number; y: number; z: number };
const palette: Record<MaterialKey, { color: string; icon: string }> = { grass: { color: "#789c54", icon: "✣" }, sand: { color: "#d5b46b", icon: "∙" }, rock: { color: "#7f8583", icon: "◆" }, gravel: { color: "#98958b", icon: "⋰" }, wood: { color: "#98633f", icon: "▥" }, water: { color: "#4d91a1", icon: "≈" } };
const key = (x: number, y: number, z: number) => `${x}:${y}:${z}`;
const terrainHeight = (x: number, z: number) => Math.max(1, Math.floor(3 + Math.sin(x * .12) * 2 + Math.cos(z * .1) * 2 + Math.sin((x + z) * .28) * .8));
const terrainKind = (x: number, z: number, height: number): MaterialKey => height <= 2 ? "sand" : height >= 7 ? "rock" : Math.abs(Math.sin(x * .23) + Math.cos(z * .2)) > 1.35 ? "gravel" : "grass";
export function VoxelGame() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const [selected, setSelected] = useState<MaterialKey>("grass");
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const engine = new Engine(canvas, true); const scene = new Scene(engine); scene.clearColor = new Color4(.52, .73, .79, 1); scene.fogMode = Scene.FOGMODE_EXP2; scene.fogDensity = .012; scene.fogColor = new Color3(.52, .73, .79); new HemisphericLight("sky", new Vector3(0, 1, 0), scene).intensity = .8; const sun = new DirectionalLight("sun", new Vector3(-.5, -1, -.35), scene); sun.position = new Vector3(30, 45, 20); sun.intensity = 1.2;
    const materials = Object.fromEntries(Object.entries(palette).map(([name, value]) => { const material = new StandardMaterial(name, scene); material.diffuseColor = Color3.FromHexString(value.color); material.specularColor = new Color3(.04, .04, .04); return [name, material]; })) as Record<MaterialKey, StandardMaterial>; const blocks = new Map<string, Block>();
    const addBlock = (x: number, y: number, z: number, kind: MaterialKey) => { const mesh = MeshBuilder.CreateBox(`block-${x}-${y}-${z}`, { size: 1 }, scene); mesh.position.set(x, y + .5, z); mesh.material = materials[kind]; blocks.set(key(x, y, z), { mesh, x, y, z }); };
    for (let x = -28; x <= 28; x++) for (let z = -28; z <= 28; z++) { const height = terrainHeight(x, z); for (let y = 0; y < height; y++) addBlock(x, y, z, y === height - 1 ? terrainKind(x, z, height) : height < 3 ? "sand" : "rock"); }
    for (let x = -22; x <= 22; x += 11) for (let z = -20; z <= 20; z += 13) { const y = terrainHeight(x, z); if (terrainKind(x, z, y) === "grass") { addBlock(x, y, z, "wood"); addBlock(x, y + 1, z, "wood"); addBlock(x, y + 2, z, "grass"); addBlock(x + 1, y + 2, z, "grass"); addBlock(x, y + 2, z + 1, "grass"); } }
    const camera = new ArcRotateCamera("player", -Math.PI / 2, Math.PI / 2.55, .2, new Vector3(0, 5, 0), scene); camera.attachControl(canvas, true); camera.lowerRadiusLimit = camera.upperRadiusLimit = .2; camera.minZ = .1; camera.keysUp = [87]; camera.keysDown = [83]; camera.keysLeft = [65]; camera.keysRight = [68]; camera.speed = .2; camera.inertia = .08; camera.angularSensibilityX = 3500; camera.angularSensibilityY = 3500;
    const pointerHandler = (event: PointerEvent) => { if (event.button !== 0 && event.button !== 2) return; event.preventDefault(); const ray = scene.createPickingRay(scene.getEngine().getRenderWidth() / 2, scene.getEngine().getRenderHeight() / 2, scene.getTransformMatrix(), camera); const hit = scene.pickWithRay(ray, mesh => mesh.name.startsWith("block-")); if (!hit?.hit || !hit.pickedMesh) return; const picked = [...blocks.values()].find(block => block.mesh === hit.pickedMesh); if (!picked) return; if (event.button === 2) { if (picked.y > 0) { picked.mesh.dispose(); blocks.delete(key(picked.x, picked.y, picked.z)); } } else { const normal = hit.getNormal(); if (!normal) return; const x = picked.x + Math.round(normal.x), y = picked.y + Math.round(normal.y), z = picked.z + Math.round(normal.z); if (!blocks.has(key(x, y, z)) && y >= 0) addBlock(x, y, z, selected); } };
    canvas.addEventListener("pointerdown", pointerHandler); canvas.addEventListener("contextmenu", event => event.preventDefault()); engine.runRenderLoop(() => scene.render()); const resize = () => engine.resize(); window.addEventListener("resize", resize); return () => { window.removeEventListener("resize", resize); canvas.removeEventListener("pointerdown", pointerHandler); scene.dispose(); engine.dispose(); };
  }, [selected]);
  return <main className="game-shell"><canvas ref={canvasRef} className="game-canvas" aria-label="Voxel world" /><div className="crosshair" aria-hidden="true"><span /><span /></div><div className="material-tray" aria-label="Building materials">{(Object.keys(palette) as MaterialKey[]).map(material => <button key={material} className={`material-swatch ${selected === material ? "selected" : ""}`} style={{ "--swatch": palette[material].color } as React.CSSProperties} onClick={() => setSelected(material)} aria-label={material}><span>{palette[material].icon}</span></button>)}</div></main>;
}
